<?php
/**
 * Created by IntelliJ IDEA.
 * User: An Wei
 * Date: 2018/11/13
 * Time: 7:25 PM
 */

namespace console\controllers\Server;

use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Http\Server;
use yii\redis\Connection;

use yii\base\Controller;

class Base extends Controller
{
    /** @var  Connection */
    public $redis;

    /**
     * @return Request
     */
    protected function getRequest(){
        return \Yii::$app->get('swoole')->request;
    }

    /**
     * @return Response
     */
    protected function getResponse(){
        return \Yii::$app->get('swoole')->response;
    }

    /**
     * @return Server
     */
    protected function getServer(){
        return \Yii::$app->get('swoole')->server;
    }

    public function init()
    {
        $this->redis = \Yii::$app->redis;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $ret = new \stdClass();
        $ret->data = $result;
        return parent::afterAction($action, $ret); // TODO: Change the autogenerated stub
    }
}